# Generated by Django 3.0.6 on 2020-05-10 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='story',
            name='created_at',
        ),
    ]
