# Generated by Django 3.0.6 on 2020-05-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='novel_num',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_num',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_num',
            field=models.PositiveIntegerField(),
        ),
    ]
