# Generated by Django 3.0.6 on 2020-05-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200510_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
