# Generated by Django 3.0.1 on 2020-05-07 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentimage',
            old_name='content_image',
            new_name='image',
        ),
    ]
