# Generated by Django 3.0.6 on 2020-05-09 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
