# Generated by Django 3.0.6 on 2020-05-09 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200509_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='updated_at',
        ),
    ]
