# Generated by Django 3.0.6 on 2020-05-09 08:33

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_new_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='text',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
