from django.urls import path
from . import views
from blog.views import (
    IndexView,
    PostDetailView,
    CategoryListView,
    CategoryPostView,
    TagListView,
    TagPostView,
    SearchPostView,
    CommentFormView,
    comment_approve,
    comment_remove,
    ReplyFormView,
    reply_approve,
    reply_remove,
    NewsView,
    MemberView,
    NovelView,
    ChapterView,
    StoryView,
    Story_DetailView,
    LaterView,
)

app_name = 'blog'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('later/', LaterView.as_view(), name='later'),
    path('novel/', NovelView.as_view(), name='novel'),
    path('novel/<int:novel_pk>/chapter/', ChapterView.as_view(), name='chapter'),
    path('novel/<int:novel_pk>/chapter/<int:chapter_pk>/story/', StoryView.as_view(), name='story'),
    path('novel/<int:novel_pk>/chapter/<int:chapter_pk>/story/<int:story_pk>/', Story_DetailView.as_view(), name='story_detail'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('category/<str:category_slug>/',
         CategoryPostView.as_view(), name='category_post'),
    path('tags/', TagListView.as_view(), name='tag_list'),
    path('tag/<str:tag_slug>/', TagPostView.as_view(), name='tag_post'),
    path('search/', SearchPostView.as_view(), name='search_post'),
    path('comment/<int:pk>/', CommentFormView.as_view(), name='comment_form'),
    path('comment/<int:pk>/approve/', comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', comment_remove, name='comment_remove'),
    path('reply/<int:pk>/', ReplyFormView.as_view(), name='reply_form'),
    path('reply/<int:pk>/approve/', reply_approve, name='reply_approve'),
    path('reply/<int:pk>/remove/', reply_remove, name='reply_remove'),
    path('news/', NewsView.as_view(), name='news'),
    path('member/', MemberView.as_view(), name='member'),
]
